# Generated by Django 5.1.3 on 2024-12-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=255, verbose_name='Откуда забрать')),
                ('dropoff_location', models.CharField(max_length=255, verbose_name='Куда доставить')),
                ('vehicle_info', models.CharField(max_length=255, verbose_name='Что перевозим')),
                ('wheels_blocked', models.BooleanField(default=False, verbose_name='Заблокировано колёс?')),
                ('steering_blocked', models.BooleanField(default=False, verbose_name='Руль заблокирован?')),
                ('additional_comments', models.TextField(blank=True, verbose_name='Дополнительный комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
