# Generated by Django 5.1.3 on 2024-12-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='vehicle_info',
            field=models.CharField(choices=[('sedan', 'Седан'), ('suv', 'Внедорожник'), ('special', 'Спецтехника')], max_length=50, verbose_name='Что перевозим'),
        ),
        migrations.AlterField(
            model_name='request',
            name='wheels_blocked',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество заблокированных колес'),
        ),
    ]
