# Generated by Django 5.1.3 on 2024-12-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_request_vehicle_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='request',
            name='dropoff_location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Куда доставить'),
        ),
        migrations.AlterField(
            model_name='request',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='request',
            name='vehicle_info',
            field=models.CharField(choices=[('sedan', 'Седан'), ('suv', 'Внедорожник'), ('special', 'Спецтехника')], max_length=50, verbose_name='Что перевезти?'),
        ),
    ]
