# Generated by Django 5.1.3 on 2024-12-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_request_phone_number_alter_request_dropoff_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='additional_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительный комментарий'),
        ),
        migrations.AlterField(
            model_name='request',
            name='dropoff_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Куда доставить'),
        ),
        migrations.AlterField(
            model_name='request',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='request',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='request',
            name='steering_blocked',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Руль заблокирован?'),
        ),
        migrations.AlterField(
            model_name='request',
            name='vehicle_info',
            field=models.CharField(blank=True, choices=[('sedan', 'Седан'), ('suv', 'Внедорожник'), ('special', 'Спецтехника')], max_length=50, null=True, verbose_name='Что перевезти?'),
        ),
        migrations.AlterField(
            model_name='request',
            name='wheels_blocked',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество заблокированных колес'),
        ),
    ]
